### ISSUE TITLE
demo.m does not run without modifications on 2017a

### ISSUE THREAD

**Issue by mathiasunberath** [Ben-Kang/PSO-EM#1]
***mex calcQFcn_mex.c*** must be executed before run

***round2.m*** must be obtained from https://www.mathworks.com/matlabcentral/fileexchange/4261-round2

**Comment by bxk-sonavex** [comment]
Thanks for pointing out the two details.  Yes, you are right. The C code has to be compiled using mex before running the demo. No prebuilt bonaries are provided because they are OS dependent and Matlab version dependent. So the source code is provided.  

Will update the readme.  Thanks again for you valuable feedback!

**Comment by Ben-Kang** [comment]
Thanks for pointing out the two details!  The C code has to be compiled using mex before running the demo. No prebuilt binaries are provided because they are OS dependent and Matlab version dependent.

I have updated the README.  Let me know If you have other issue with running the code.  Otherwise, I will close the ticket.

**Comment by mathiasunberath** [comment]
Thanks for updating the **readme**. The demo code worked fine other than the above mentioned details, so I guess pointing these out was really all what's necessary.
